### ISSUE TITLE
[PRE REVIEW]: Running faster scripts with DaemonMode.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#73] opened 2021-08-24 07:15 UTC
**Submitting author:** @dmolina (<a href="http://orcid.org/0000-0002-4175-2204">Daniel Molina Cabrera</a>)
**Repository:** <a href=" https://github.com/dmolina/DaemonMode.jl" target ="_blank"> https://github.com/dmolina/DaemonMode.jl</a>
**Version:** 
**Editor:** @ranjanan
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**Author instructions**

Thanks for submitting your paper to JCON @dmolina. **Currently, there isn't an JCON editor assigned** to your paper.

@dmolina if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-08-24 07:15
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-08-24 07:15
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by vchuravy** [comment] 2021-09-01 12:49
@whedon assign @ranjanan as editor

**Comment by whedon** [comment] 2021-09-01 12:49
OK, the editor is @ranjanan

**Comment by dmolina** [comment] 2021-09-01 13:18
I am sorry, but I do not know why is said that there is not any paper, because in the paper/ directory there is both a paper.yml and a paper.tex with the Latex of the paper. Please, @ranjanan, could you give more information? I will be glad to fix any possible problem, but I have no information about the error.  Maybe is because I put in Repository github.com/dmolina/DaemonMode.jl instead of https://github.com/dmolina/DaemonMode.jl/? Thanks in advance for your work. 
Best regards, Daniel Molina

**Comment by vchuravy** [comment] 2021-09-01 14:16
@whedon generate pdf

**Comment by whedon** [comment] 2021-09-01 14:16
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment] 2021-10-06 23:44
@whedon generate pdf from branch master

**Comment by whedon** [comment] 2021-10-06 23:44
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment] 2021-10-06 23:57
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-06 23:57
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment] 2021-10-07 00:02
@whedon commands

**Comment by whedon** [comment] 2021-10-07 00:02
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by ranjanan** [comment] 2021-10-07 00:02
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-07 00:02
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-10-15 19:07
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by dmolina** [comment] 2021-10-15 19:08
Dear @ranjanan, I have accepted the .latexmk and also I have removed some symbols that seems to give problems in UTF-8. Please, try it again.

**Comment by ranjanan** [comment] 2021-10-15 19:09
@whedon generate pdf from branch master

**Comment by ranjanan** [comment] 2021-10-15 19:55
I don't have any error messages on my end. I am seeing exactly what you are seeing. Are you able to compile the paper locally, with the instructions on the README: https://github.com/JuliaCon/JuliaConSubmission.jl?

**Comment by dmolina** [comment] 2021-10-15 19:59
Thanks you for the quick answer. Yes, however I am going to try some changes (like moving all external files to the same directory instead of test/ directory). I will check also the instructions, I will reply you when I think the error could be fixed (I guess it will be tomorrow of next day) Thanks you for your time.

**Comment by ranjanan** [comment] 2021-10-15 20:01
Yes, I would move all external files to the paper directory if any, given [this earlier error](https://github.com/JuliaCon/proceedings-review/issues/73#issuecomment-937338999). And I would compile locally and debug. Thanks again, keep me posted!

**Comment by ranjanan** [comment] 2021-12-02 15:11
@dmolina would you mind reusing the template again? Just to reflect recent changes. Just to see if we get the same error.

**Comment by dmolina** [comment] 2021-12-03 12:30
Dear @ranjanan, I have just update the template, in particular there was several differences in the bibliography template. I have update my version (and check it is running locally). 
Please, check it again, and thank you for your work.

**Comment by ranjanan** [comment] 2021-12-03 17:41
@whedon generate pdf from branch master

**Comment by whedon** [comment] 2021-12-03 17:41
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-12-03 17:41
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment] 2021-12-03 17:41
@whedon generate pdf

**Comment by whedon** [comment] 2021-12-03 17:41
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment] 2021-12-03 17:57
@dmolina can you fix these two lines https://github.com/dmolina/DaemonMode.jl/blob/master/paper/paper.tex#L516 ? Put them in the paper folder and refer to them locally

**Comment by dmolina** [comment] 2021-12-05 11:43
Sorry for the error. Yes, I have just fixed these lines. Please, try to compile it again.

**Comment by ranjanan** [comment] 2021-12-05 16:41
@whedon generate pdf

**Comment by whedon** [comment] 2021-12-05 16:42
PDF failed to compile for issue #73 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by dmolina** [comment] 2021-12-06 11:57
I am really sorry it is still not working, any other idea? There is a way to reproduce the automatic process to generate the pdf to try to debug it?
Thanks in advance for your work.

**Comment by matbesancon** [comment] 2022-01-04 13:42
mmmmh, maybe try to recreate a paper folder based on the JuliaConSubmission.jl one, and add your files + adapt the ones already there

**Comment by ranjanan** [comment] 2022-02-27 20:50
@dmolina

**Comment by ranjanan** [comment] 2022-03-31 14:13
@dmolina

**Comment by ranjanan** [comment] 2022-04-07 14:05
@dmolina bump

**Comment by ranjanan** [comment] 2022-07-03 21:21
@dmolina

**Comment by ranjanan** [comment] 2023-01-09 17:15
@dmolina I am going to close this. If you'd like to proceed with this, please let me know and I'm happy to reopen.

**Closed by ranjanan** 2023-01-09 17:15 UTC
Labels: pre-review, author action required

**Comment by lucaferranti** [comment] 2024-04-25 17:29
@editorialbot reject
