### ISSUE TITLE
[PRE REVIEW]: CompositionalNetworks.jl: a scaling glass-box neural network to learn combinatorial functions

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#87] opened 2021-09-30 17:26 UTC
**Submitting author:** @azzaare (<a href="http://orcid.org/0000-0002-8800-6356">Jean-François Baffier</a>)
**Repository:** <a href="https://github.com/JuliaConstraints/CompositionalNetworks.jl" target ="_blank">https://github.com/JuliaConstraints/CompositionalNetworks.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @azzaare. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@azzaare if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-09-30 17:26
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-09-30 17:27
PDF failed to compile for issue #87 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-09-30 17:27
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1481.2 files/s, 82011.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           15            165             45           1036
Markdown                        10             81              0            197
YAML                             3              0              0            105
TOML                             2              4              0             28
-------------------------------------------------------------------------------
SUM:                            30            250             45           1366
-------------------------------------------------------------------------------


Statistical information for the repository '790bd4ab64c105e4375ad534' was
gathered on 2021/09/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2021-10-07 01:32
```
Attempting PDF compilation from custom branch main. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-10-07 01:33
PDF failed to compile for issue #87 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-10-07 01:43
PDF failed to compile for issue #87 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'placeins.sty' from line
  '! LaTeX Error: File `placeins.sty' not found.'
Latexmk: Missing input file: 'placeins.sty' from line
  '! LaTeX Error: File `placeins.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by Azzaare** [comment] 2021-10-07 01:47
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-07 01:47
PDF failed to compile for issue #87 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by Azzaare** [comment] 2021-10-07 02:07
@matbesancon I have tried to solve the building error, but I can't reproduce it on my local machine (in the sense that it build perfectly with `latexmk -bibtex -pdf paper.tex`. And I don't have the access to the log. Any idea of what I should do now?

**Comment by whedon** [comment] 2021-10-07 14:19
OK, the editor is @matbesancon

**Comment by Azzaare** [comment] 2021-10-08 00:47
@whedon generate pdf

**Comment by Azzaare** [comment] 2021-10-08 00:49
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-08 00:49
PDF failed to compile for issue #87 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by Azzaare** [comment] 2021-10-08 01:02
@matbesancon thanks. It was part of the problem. I also had one incompatible package with the class, but it was not critical, so it is fixed now.

**Comment by matbesancon** [comment] 2022-01-27 15:41
@Azzaare let us know when your updates are done

**Comment by Azzaare** [comment] 2022-02-10 04:03
Hi @matbesancon 
Thank you for the reminder, I had some unexpected things to handle and forgot to check github.

**Comment by luraess** [comment] 2023-09-07 20:30
Dear author, we are in the process of resuming the stalled JuliaCon reviews. If you are still interested in getting your work published, please start addressing the author-action-required items within the coming 3 weeks. If no action is taken within the coming 3 weeks, we will close the submission. Thank you for your understanding. The new editorial team

**Closed** 2023-10-08 19:18 UTC
Labels: pre-review, Julia, author action required

**Comment by Azzaare** [comment] 2023-10-17 09:17
@luraess Sorry for the late reply. Due to some unforeseen circumstances of one of the quthor, a paper linked to this one has been delayed for years. I am working (slowly) at doing the related part so that I could update this one.

It won't be ready for months though so, it is better to properly close this issue.

Thank you for the time you took, and we will incorporate all review comments  once we are able to submit here again (probably through a talk at the next JuliaCon as we are extending our work on the topic).
