### ISSUE TITLE
[REVIEW]: High-performance xPU Stencil Computations in Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#138] opened 2023-11-06 19:53 UTC
**Submitting author:** @omlins (<a href="http://orcid.org/0000-0001-8969-5619">Samuel Omlin</a>)
**Repository:** https://github.com/omlins/ParallelStencil.jl
**Branch with paper.md** (empty if default branch): JuliaConProceeding2022
**Version:** v1
**Editor:** @fcdimitr
**Reviewers:** @georgebisbas, @bgeihe
**Archive:** 10.5281/zenodo.13847580

 

## Status

[![status](https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f/status.svg)](https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f"><img src="https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f/status.svg)](https://proceedings.juliacon.org/papers/c28f9f11e3123ebaa856aeca43962b5f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/omlins/ParallelStencil.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@georgebisbas & @bgeihe, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fcdimitr know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/omlins/ParallelStencil.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@omlins) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/omlins/ParallelStencil.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@omlins) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment] 2023-11-06 19:53
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @georgebisbas, @sloede it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2023-11-06 19:53
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (1239.6 files/s, 187708.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           62            887            552           8623
Markdown                         1            130              0            435
YAML                             2              3              2             55
TOML                             6             10              0             54
-------------------------------------------------------------------------------
SUM:                            71           1030            554           9167
-------------------------------------------------------------------------------


Statistical information for the repository '04166151f14578eb224e9fe1' was
gathered on 2023/11/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2023-11-06 19:53
PDF failed to compile for issue #138 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by fcdimitr** [comment] 2023-11-06 19:53
@whedon generate pdf from branch JuliaConProceeding2022

**Comment by whedon** [comment] 2023-11-06 19:54
```
Attempting PDF compilation from custom branch JuliaConProceeding2022. Reticulating splines etc...
```

**Comment by whedon** [comment] 2023-11-06 19:54
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00138/jcon.00138/10.21105.jcon.00138.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00138/jcon.00138/10.21105.jcon.00138.pdf) :page_facing_up: :point_left:

**Comment by fcdimitr** [comment] 2023-11-06 19:55
@whedon check references

**Comment by fcdimitr** [comment] 2023-11-06 19:57
@whedon check references from branch JuliaConProceeding2022

**Comment by whedon** [comment] 2023-11-06 19:57
```
Attempting to check references... from custom branch JuliaConProceeding2022
```

**Comment by whedon** [comment] 2023-11-06 19:57
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/SC41405.2020.00062 is OK
- ??? is OK
- 10.21105/jcon.00068 is OK
- 10.5194/gmd-15-5757-2022 is OK

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.1109/tpds.2018.2872064 may be a valid DOI for title: Effective extensible programming: unleashing Julia on GPUs

INVALID DOIs

- None
```

**Comment by fcdimitr** [comment] 2023-11-07 13:43
@whedon remove @sloede as reviewer

**Comment by whedon** [comment] 2023-11-07 13:43
OK, @sloede is no longer a reviewer

**Comment by fcdimitr** [comment] 2023-11-07 13:44
@whedon add @bgeihe as reviewer

**Comment by whedon** [comment] 2023-11-07 13:44
OK, @bgeihe is now a reviewer

**Comment by fcdimitr** [comment] 2023-11-07 13:44
@whedon re-invite @bgeihe as reviewer

**Comment by whedon** [comment] 2023-11-07 13:44
The reviewer already has a pending invite.

@bgeihe please accept the invite by clicking this link: https://github.com/JuliaCon/proceedings-review/invitations

**Comment by fcdimitr** [comment] 2023-11-07 13:45
@bgeihe thank you for volunteering as a reviewer. You can find more details on the JuliaCon review process [here](https://juliacon.github.io/proceedings-guide/reviewer/). Feel free to ask me any questions you have.

**Comment by bgeihe** [comment] 2023-11-17 15:25
### Review

ParallelStencil.jl is a package which allows to implement efficient algorithms based on stencil computations. Its special feature is being architecture-agnostic, which means that the same code can be used for prototyping and high performance computations on either CPUs or GPUs.

The extended abstract is written clearly and concisely. Motivation is given, the approach for implementation is sketched, and numerical examples for 3D heat diffusion as well as nonlinear problems are presented. The impressive results demonstrate the claimed near optimal performance.

I have linked three issues with suggestions as to minor modifications. Once these have been addressed, I think the extended abstract should be accepted for publication.

**Comment by whedon** [comment] 2023-11-20 19:53
:wave: @georgebisbas, please update us on how your review is going (this is an automated reminder).

**Comment by georgebisbas** [comment] 2023-11-25 14:06
ParallelStencil.jl offers a high-level textbook-math-close interface and abstractions for solving PDEs for the HPC solution of PDEs. It can also support explicit stencil definition and computation. Users can benefit from seamlessly transitioning the high-level code to target both CPUs and GPUs, with only minor to no edits in the source code.


This work has a high overlap with  https://github.com/JuliaCon/proceedings-review/issues/137
I propose that they be merged into a paper covering both packages. However, this is not a firm requirement. Since ParallelStencil.jl does not claim distributed-memory parallelism benefits, mentions to DMP should be removed to reduce the overlap. For example:

Abstract: …and multiple dispatch enable writing a single code that is suitable for both productive proto typing on a single CPU thread and production runs on multi-GPU or CPU workstations or supercomputers….

Another suggestion is to avoid using the term xPU in the title. In the recent rise of “exotic” accelerators like Google’s TPU, Graphcore’s IPU, or expected QPUs, it probably would not harm just to use: 

High-performance Stencil Computations in Julia

And just make it clear that this work is about CPU and GPU.



The package's functionality is confirmed, and the installation, testing and use documentation is present and well-defined.


The paper is well-written, clearly presenting the motivation and example usage of the package. This work also benefits from the math-close interface, which is only sometimes provided in the stencil-specific scientific community. Projects like OpenSBLI, Devito, and Exastencils provide such interfaces, primarily not in Julia. The paper would probably benefit by slightly “upgrading” the reference to the symbolic interface, as this helps interdisciplinary scientists take advantage of HPC solvers without the need to entangle with low-level HPC optimisations.


The diffusion example presented is well-written. Minor comments (not aiming to be addressed, but possibly interesting points for future work and further discussion):
Could the use of both “dx” and “_dx” possibly be avoided? As far as I understand, it only helps to reduce the text in equations present in the parallel loop (lines 5:12) while only adding more complexity (with no comments in line 26).
Additionally, T2 in line 30 is the stencil computation's second buffer. Does this mean the user would need to add additional copies if the PDE solvers require a higher accuracy order in time? (e.g. time discretisation order in acoustic wave propagation is 2 (needing T, T2, T3?))
- Should Figure 1 be presented as a Listing 1?
- Should Figure 2 be split into two subfigures?

Performance evaluation: Linked issue in the package repository.

**Comment by omlins** [comment] 2023-12-07 19:29
@bgeihe : Thank you very much for the careful review. We are working on addressing the reviews, including the issues you have opened.

**Comment by omlins** [comment] 2023-12-07 20:10
@georgebisbas : Thank you very much for the careful review. We are working on addressing the reviews. In the following you can find replies to two of the issues that you raised. We will respond to the remaining issues alongside with the improvements of the manuscript.

> This work has a high overlap with https://github.com/JuliaCon/proceedings-review/issues/137
I propose that they be merged into a paper covering both packages. However, this is not a firm requirement. Since ParallelStencil.jl does not claim distributed-memory parallelism benefits, mentions to DMP should be removed to reduce the overlap. For example:
Abstract: …and multiple dispatch enable writing a single code that is suitable for both productive proto typing on a single CPU thread and production runs on multi-GPU or CPU workstations or supercomputers….

Thank you for pointing out the overlaps concerning distributed memory parallelism. We will remove it as much as possible in order to publish the packages ParallelStencil.jl and ImplicitGlobalGrid.jl in separate papers. We would like to keep the format of one paper per package, given that they have a different focus and can be used independently.

> Performance evaluation: Linked issue in the package repository.

We have replied to this issue directly where it was opened.

**Comment by fcdimitr** [comment] 2024-03-06 01:05
Hi @omlins! I'm just checking in; what is the status of this? Thank you!

**Comment by fcdimitr** [comment] 2024-03-21 15:14
@editorialbot generate pdf

**Comment by fcdimitr** [comment] 2024-03-21 15:19
@editorialbot set JuliaConProceeding2022 as branch

**Comment by fcdimitr** [comment] 2024-03-21 15:19
@editorialbot generate pdf

**Comment by lucaferranti** [comment] 2024-03-21 15:23
The error above is expecetd and known. The new infrastructure is mainly in place, the only piece missing is the generation of the xml file, which is what the error is comlaining about

**Comment by fcdimitr** [comment] 2024-03-23 17:34
@editorialbot generate pdf

**Comment by fcdimitr** [comment] 2024-03-23 17:39
The error might be due to missing DOIs. @lucaferranti is my understanding correct?

@omlins could you add the missing DOIs and try to generate the PDF again?

Thank you!

**Comment by omlins** [comment] 2024-03-25 19:31
@fcdimitr : please excuse the delay for the reply. We aim to finalize this extended abstract hopefully this and next week. 

I have updated the bibliography file; I think now it should be able to generate the PDF.

**Comment by lucaferranti** [comment] 2024-03-25 19:47
> The error might be due to missing DOIs. @lucaferranti is my understanding correct?

sorry for the delay in replying, but I think it's correct, ping me if htere are still issues with editorialbot

**Comment by fcdimitr** [comment] 2024-03-25 19:58
@editorialbot generate pdf

**Comment by fcdimitr** [comment] 2024-05-29 14:54
Hi @omlins! I'm just checking in; what is the status of this? Thank you!

**Comment by omlins** [comment] 2024-07-23 15:23
We aim to address the remaining issues in the manuscript in the next couple of days. Please excuse the delay.

**Comment by omlins** [comment] 2024-07-25 18:11
Verifying that generating PDF still works before pushing changes

**Comment by omlins** [comment] 2024-07-25 18:11
@editorialbot generate pdf

**Comment by luraess** [comment] 2024-07-29 12:02
@editorialbot generate pdf

**Comment by omlins** [comment] 2024-07-30 16:43
@editorialbot generate pdf

**Comment by omlins** [comment] 2024-07-30 17:10
Dear reviewers, we have improved the manuscript, addressing all the issues raised. @georgebisbas @bgeihe

**Comment by omlins** [comment] 2024-07-30 17:13
@benegee

**Comment by georgebisbas** [comment] 2024-07-31 08:30
Thank you @omlins!
After having a pass over the applied edits, I think that all the main points have been successfully addressed.

**Comment by benegee** [comment] 2024-08-14 13:47
I agree!

**Comment by omlins** [comment] 2024-08-21 09:08
@fcdimitr : both reviewers have approved the edits

**Comment by fcdimitr** [comment] 2024-09-03 13:36
@editorialbot accept

**Comment by fcdimitr** [comment] 2024-09-03 13:36
Hi @omlins! Sorry for the delay. Could you please check the Zenodo archive that is required for acceptance? Thanks!

**Comment by fcdimitr** [comment] 2024-09-03 16:43
@editorialbot recommend-accept

**Comment by omlins** [comment] 2024-10-02 17:07
@fcdimitr : here you can find the DOI for the paper: https://doi.org/10.5281/zenodo.13882412
here you can find the DOI for the code: https://doi.org/10.5281/zenodo.13847580
Please excuse the delay.

**Comment by luraess** [comment] 2024-10-02 17:13
And as version number we could set and use the `v1` tag from the paper.

**Comment by luraess** [comment] 2024-10-07 07:55
@fcdimitr could we get the final actions done here in order to have the paper out? Thanks!

**Comment by fcdimitr** [comment] 2024-10-08 00:50
@editorialbot set 10.5281/zenodo.13847580 as archive

**Comment by fcdimitr** [comment] 2024-10-08 00:50
@editorialbot set v1 as version

**Comment by fcdimitr** [comment] 2024-10-08 00:50
@editorialbot recommend-accept

**Comment by fcdimitr** [comment] 2024-10-08 00:54
@editorialbot accept

**Closed** 2024-10-08 01:10 UTC
Labels: Julia, review, accepted, author action required, recommend-accept, published

**Comment by luraess** [comment] 2024-10-08 06:30
Thank you for handling the paper @fcdimitr 🙏 Glad to see it published!

**Comment by luraess** [comment] 2024-10-31 17:04
@fcdimitr Can you set the following:
- the code DOI to https://doi.org/10.5281/zenodo.13847579
- the paper DOI to https://doi.org/10.5281/zenodo.13882411
- the paper version to v2

and then trigger the `@editorialbot reaccept` (maybe running first, if it would work, the `recommend-accept` command to produce the proof I could check)

**Comment by fcdimitr** [comment] 2024-10-31 19:26
@editorialbot set v2 as version

**Comment by fcdimitr** [comment] 2024-10-31 19:26
@editorialbot recommend-accept

**Comment by fcdimitr** [comment] 2024-10-31 19:30
@editorialbot reaccept
