### ISSUE TITLE
[REVIEW]: MutableArithmetics: An API for mutable operations

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#93] opened 2021-10-16 02:25 UTC
**Submitting author:** @blegat (<a href="http://orcid.org/0000-0002-5921-368X">Benoît Legat</a>)
**Repository:** https://github.com/jump-dev/MutableArithmetics.jl/
**Branch with paper.md** (empty if default branch): 
**Version:** v1.4.3
**Editor:** @lucaferranti
**Reviewers:** @schillic, @ksil
**Archive:** 10.5281/zenodo.10985724

 

## Status

[![status](https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01/status.svg)](https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01"><img src="https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01/status.svg)](https://proceedings.juliacon.org/papers/7768893900f2b6be4bac7e16b843bd01)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jump-dev/MutableArithmetics.jl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ksil, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @ranjanan know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jump-dev/MutableArithmetics.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@blegat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jump-dev/MutableArithmetics.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@blegat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment] 2021-10-16 02:25
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ksil it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-10-16 02:25
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment] 2021-10-16 02:25
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1137/15M1020575 is OK
- 10.5281/zenodo.5083796 is OK
- 10.1145/3087604.3087611 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-10-16 02:25
Wordcount for `paper.tex` is 2993

**Comment by whedon** [comment] 2021-10-16 02:25
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: :point_left:

**Comment by ranjanan** [comment] 2021-10-16 02:26
@whedon commands

**Comment by ranjanan** [comment] 2021-10-16 02:26
@whedon list reviewers

**Comment by whedon** [comment] 2021-10-16 02:26
Here's the current list of reviewers: http://bit.ly/2V9GSFq

**Comment by ranjanan** [comment] 2021-10-16 02:27
@whedon add @tkf as reviewer

**Comment by whedon** [comment] 2021-10-16 02:27
OK, @tkf is now a reviewer

**Comment by whedon** [comment] 2021-10-16 02:29
@tkf already has access.

**Comment by blegat** [comment] 2021-11-01 23:06
Thank you for the review, I have updated the paper using your suggestions.

**Comment by blegat** [comment] 2021-11-01 23:06
@whedon generate pdf

**Comment by whedon** [comment] 2021-11-01 23:07
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: :point_left:

**Comment by ksil** [comment] 2021-11-03 04:43
"This examples encapsulates" on page 1 should be "This example encapsulates", and "is a the core" should be "is at the core" on page 3. Otherwise, with those changes, everything looks good to me @ranjanan

**Comment by blegat** [comment] 2021-11-03 13:35
Thanks your for noticing this and sorry I missed these in your comments, I just fixed these two typos.

**Comment by blegat** [comment] 2021-11-03 13:35
@whedon generate pdf

**Comment by whedon** [comment] 2021-11-03 13:36
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00093/jcon.00093/10.21105.jcon.00093.pdf) :page_facing_up: :point_left:

**Comment by ranjanan** [comment] 2022-02-10 15:06
@tkf another reminder to submit your review

**Comment by ranjanan** [comment] 2022-02-27 20:50
@tkf

**Comment by ranjanan** [comment] 2022-04-07 14:06
@tkf bump

**Comment by ranjanan** [comment] 2022-04-15 19:40
@tkf

**Comment by ranjanan** [comment] 2022-07-03 21:21
@tkf

**Comment by ranjanan** [comment] 2022-12-12 19:30
@whedon remove @tkf as reviewer

**Comment by whedon** [comment] 2022-12-12 19:31
OK, @tkf is no longer a reviewer

**Comment by ranjanan** [comment] 2022-12-12 19:31
@whedon add @aviatesk as reviewer

**Comment by whedon** [comment] 2022-12-12 19:31
OK, @aviatesk is now a reviewer

**Comment by ranjanan** [comment] 2023-01-09 17:14
@aviatesk just a reminder for this review.

**Comment by matbesancon** [comment] 2023-09-07 14:31
@whedon assign @lucaferranti as editor

**Comment by lucaferranti** [comment] 2023-09-07 14:36
@blegat I'll be the new editor for this submission. 

@aviatesk :wave: , are you still willing to review this?

**Comment by lucaferranti** [comment] 2023-09-26 13:31
@schillic agreed to review this submission. 

Christian, you can find the review process guidelines [here](https://juliacon.github.io/proceedings-guide/reviewer/), if you have any questions do let me know.

**Comment by lucaferranti** [comment] 2023-09-26 13:32
@whedon help

**Comment by whedon** [comment] 2023-09-26 13:32
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lucaferranti** [comment] 2023-09-26 13:32
@whedon commands

**Comment by whedon** [comment] 2023-09-26 13:32
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment] 2023-09-26 13:32
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-09-26 13:33
@whedon generate pdf

**Comment by whedon** [comment] 2023-09-26 13:33
PDF failed to compile for issue #93 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by lucaferranti** [comment] 2023-10-06 18:20
@whedon assign lucaferranti as editor

**Comment by whedon** [comment] 2023-10-06 18:20
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-06 18:21
@whedon remove aviatesk as reviewer

**Comment by whedon** [comment] 2023-10-06 18:21
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-09 09:33
@whedon assign lucaferranti as editor

**Comment by whedon** [comment] 2023-10-09 09:33
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-09 09:33
@whedon remove aviatesk as reviewer

**Comment by whedon** [comment] 2023-10-09 09:33
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-09 09:34
@whedon remove @aviatesk as reviewer

**Comment by whedon** [comment] 2023-10-09 09:34
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-09 17:12
@whedon assign @lucaferranti as editor

**Comment by whedon** [comment] 2023-10-09 17:13
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-09 17:13
@whedon assign @schillic as reviewer

**Comment by whedon** [comment] 2023-10-09 17:13
I'm sorry @lucaferranti, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by lucaferranti** [comment] 2023-10-10 05:43
@arfon it seems I still dont have the required rights, do you know if there's something missing?

**Comment by schillic** [comment] 2023-10-10 05:49
I thought I would have more time, but no. The next three weeks are still packed with more urgent tasks. I will try, but if not, I can definitely review in November.

**Comment by matbesancon** [comment] 2023-10-10 07:27
@whedon assign @lucaferranti as editor

**Comment by matbesancon** [comment] 2023-10-10 07:28
@whedon assign lucaferranti as editor

**Comment by arfon** [comment] 2023-10-10 17:54
@whedon list editors

**Comment by whedon** [comment] 2023-10-10 17:54
Current editors:

```
@arfon
@carstenbauer
@fcdimitr
@lucaferranti
@luraess
@matbesancon
@odow
@pitsianis
@ranjanan
@vchuravy
```

**Comment by arfon** [comment] 2023-10-10 17:54
Can you try again now @lucaferranti and @matbesancon ?

**Comment by lucaferranti** [comment] 2023-10-10 18:01
@whedon remove @aviatesk as reviewer

**Comment by whedon** [comment] 2023-10-10 18:01
OK, @aviatesk is no longer a reviewer

**Comment by lucaferranti** [comment] 2023-10-10 18:01
@whedon assign @schillic as reviewer

**Comment by whedon** [comment] 2023-10-10 18:01
OK, @schillic is now a reviewer

**Comment by lucaferranti** [comment] 2023-10-10 18:02
@whedon list commands

**Comment by lucaferranti** [comment] 2023-10-10 18:02
@whedon commands

**Comment by lucaferranti** [comment] 2023-10-10 18:03
@whedon remove @schillic as reviewer

**Comment by whedon** [comment] 2023-10-10 18:03
OK, @schillic is no longer a reviewer

**Comment by lucaferranti** [comment] 2023-10-10 18:03
@whedon add @schillic as reviewer

**Comment by whedon** [comment] 2023-10-10 18:03
OK, @schillic is now a reviewer

**Comment by lucaferranti** [comment] 2023-10-10 18:04
@whedon add @ksil as reviewer

**Comment by whedon** [comment] 2023-10-10 18:04
OK, @ksil is now a reviewer

**Comment by lucaferranti** [comment] 2023-10-10 18:05
@arfon seems to work now.

Quick question, is there a way to generate a new review checklist for christian? (who replaced the previous reviewer)

**Comment by lucaferranti** [comment] 2023-11-07 09:07
@whedon generate pdf

**Comment by whedon** [comment] 2023-11-07 09:08
PDF failed to compile for issue #93 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by lucaferranti** [comment] 2023-11-07 09:08
@blegat it seems the paper does not compile anymore, can you look into it?

**Comment by lucaferranti** [comment] 2023-11-07 09:08
@whedon re-invite @schillic as reviewer

**Comment by whedon** [comment] 2023-11-07 09:09
@schillic already has access.

**Comment by lucaferranti** [comment] 2023-11-07 09:10
@schillic can you try if you can edit the checklist assigned to `aviatesk`? If so, I can simply update the name there

**Comment by blegat** [comment] 2023-11-07 09:25
@lucaferranti I have tried `latexmk -bibtex -pdf paper.tex`  suggested by the [author guide](https://juliacon.github.io/proceedings-guide/author/) and it works locally. Is there any way to see the log of whedon's build ?

**Comment by schillic** [comment] 2023-11-07 14:46
@lucaferranti I can edit. What is need is time :)
I am at a workshop right now. I hope to get to this next week. Sorry for the delay.

**Comment by lucaferranti** [comment] 2023-11-07 14:52
@blegat unfortunately logs are not accessible. This and a lot of other latex issues will be fixed once we migrate to the new `editorial-bot` (still WIP, but should happen within a few weeks).

Do notice that here we use a fairly old version of `latexmk` (`17 Jan. 2018, version: 4.55.`), so the issue might be that when updating the paper you used some latex features not supported by the older version?

**Comment by schillic** [comment] 2023-11-24 16:43
#### Summary

The paper presents a well thought through Julia package with an elegant API. The paper itself is very well written with nice motivating examples, which makes it easy to follow for a reader with basic Julia knowledge. I have a few requests to fix some code blocks and update the references, thus a *Minor modification request*. There are quite some further suggestions for improvement, but none of them is critical for publication. So @blegat I leave it to your discretion to incorporate them. Just give @lucaferranti a sign when the paper is ready from your side. I can also take a look again if you prefer. Happy to hopefully see this paper published soon!

#### Please fix

- `add_mul!(...)` should be `add_mul!!(...)` (2x in code blocks on pp. 4 & 5).
- The third code block on p. 5 starting with `buf = buffer_for(` does not execute for me (see the error below)
  - Should the `typeof`s be `eltype`s as in the first block?
  - The call to `buffered_operate!` also fails. I guess it should be the same as in the second block, just prepended by `@allocated`?
```julia
ERROR: MethodError: no method matching buffer_for(::typeof(add_mul), ::Type{Vector{BigInt}}, ::Type{Matrix{BigInt}}, ::Type{Vector{BigInt}})

Closest candidates are:
  buffer_for(::typeof(add_mul), ::Type{BigInt}...)
```
- The fourth code block on p. 5 starting with `using Polynomials` does not work because `m` is undefined. Please add the value you used so that it works and the results are reproducible.
- In the fifth code block on p. 5 (last code block in the paper), the last two commands do not work.
- References:
  - [1],[8],[9] can probably update the version
  - [5] has a published version: https://dblp.org/rec/journals/cca/GowdaMCGSER21.html?view=bibtex
  - [6] is published now: https://dblp.org/rec/journals/informs/LegatDGL22.html?view=bibtex
  - [7] should use proper capitalization

#### Checklist comments

- A statement of need: While there is no dedicated section, the purpose of the package is clearly communicated.
- Installation instructions: While there are no instructions, the standard `Pkg` installation is smooth. I consider this sufficient.
- Community guidelines: While there are no guidelines in the README or documentation, I believe jump-dev is well known in the community and is easy to reach out to. Nevertheless, maybe you want to include a link in the README.

#### Suggestions

- I guess you want to update your affiliation.
- I suggest to avoid the page breaks in code blocks. You can wrap the `jllisting`s in a `minipage` environment, possibly with some negative `\vspace` at the beginning (I tried it and it works).
- I suggest to define a hyphenation rule for "MutableArithmetics" via `\hyphenation{Mutable-Arithmetics}`.
- abstract: "talk" -> "package" (or "paper")
- p. 1:
  - "when summing the elements of an array" - I did not understand this example at this point (why would you mutate the array here?). I find the other example (array multiplication) sufficiently convincing, so maybe the first example can just be dropped here; maybe the multiplication example can be generalized to array arithmetic (because I do not think there is anything special about multiplication).
  - Footnote 1 is missing a period in the end.
  - "multiple precision numbers" -> I would write "multiple-precision numbers" for clarity.
  - In the enumeration with (1) and (2) I would start with "MutableArithmetics" instead of "it".
  - "e.g" -> "e.g.,"
  - When recalling (1) and (2) via `\ref`, I would use `\eqref` to get the parentheses (2x).
  - "on top of the MutableArithmetics API" - I am not sure what this is supposed to mean. Maybe it can simply be removed?
  - "Julia sum function" -> "Julia's sum function"
  - "cases where" -> "cases, where"
  - "a linear combinations" -> "linear combinations"
- p. 2:
  - code blocks: Maybe indent lines that continue from the previous line (e.g., by two spaces).
  - "would fallback" -> "would fall back"
  - "writing a code that should" -> I would say "writing code to" or "writing a function to".
  - "the rational Julia type" - I would use green "Rational" as you do for BigInt etc. to avoid an ambiguity here. I would also flip to "the Julia Rational type" or even drop "Julia" altogether.
  - I am not sure about referring back to footnote 1 two more times here. You already clarified what you mean by "mutate", so I do not see the need to repeat that. But I guess this is a matter of taste.
  - "of rational number introduces" -> "of rational numbers introduced"
  - "may mutate [...] should mutate" - I would emphasize (`\emph`) "may" and "should".
  - In the last code block, `function Base.:*(A::Matrix{S}, b::Vector{T})` leads to an error because `S` and `T` are undefined (not very relevant because the whole code block does not compile (on purpose) anyway).
- p. 3:
  - "mutate^1 args[1]" -> "mutates^1 args[1]"
  - "operations so" -> "operations, so"
  - "each pairs" -> "each pair"
  - "value of the result need" -> "value of the result needs"
  - "the non-mutable type" -> "the non-mutable types"
  - The first method in the last code block could use the short notation (`promote_operation(...) = Foo`). I mention this because you used it elsewhere.
- p. 4:
  - The second code block in Section 4 is missing the squaring (`^2`).
  - The output of BenchmarkTools has looks quite different (see below). I do not suggest to change the output in the paper and just wanted to give a heads up.
  - "multiple occurence" -> "multiple occurrences"
  - The first method in the last code block could again use the short notation.
  - "there is only 48 bytes" -> "there are only 48 bytes"
  - "this is the allocation" -> "which is the allocation"
  - The last code block has a `where {N}` that is not needed.
```julia
BenchmarkTools.Trial: 334 samples with 1 evaluation.
 Range (min … max):   7.181 ms … 105.259 ms  ┊ GC (min … max):  0.00% … 53.51%
 Time  (median):      7.376 ms               ┊ GC (median):     0.00%
 Time  (mean ± σ):   15.003 ms ±  24.655 ms  ┊ GC (mean ± σ):  28.72% ± 14.81%

  █                                                             
  ██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇█▆▅ ▅
  7.18 ms       Histogram: log(frequency) by time      99.1 ms <

 Memory estimate: 3.67 MiB, allocs estimate: 198166.
```
- p. 5:
  - "higher level operations" -> "higher-level operations"
  - "one of the motivation" -> "one of the motivations" or "one motivation"
  - "a interface" -> "an interface"
  - "expressions but" -> "expressions, but"
  - "of implementation of" -> "of implementing" (sounds better)
- acknowledgments: The last paragraph should be updated (there is only one author).

**Comment by schillic** [comment] 2023-11-24 16:46
@lucaferranti: I ticked off the checklist. I left "Functionality" open to address the fixes to the code blocks as indicated in my review.

**Comment by lucaferranti** [comment] 2024-01-19 15:52
@blegat did you have time to look at Christian's comments?

**Comment by blegat** [comment] 2024-01-20 10:18
Thanks for the reminder, I'll do it next week

**Comment by whedon** [comment] 2024-02-13 13:58
PDF failed to compile for issue #93 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by lucaferranti** [comment] 2024-03-23 08:45
@editorialbot generate pdf

**Comment by lucaferranti** [comment] 2024-03-23 08:48
jippiie we have the new editorialbot and paper compilation works :tada: 

@blegat @schillic can you remind me the status of the review?

**Comment by lucaferranti** [comment] 2024-03-23 08:50
ouch inline code snippets look a bit ugly?

**Comment by blegat** [comment] 2024-03-26 13:52
I've now addressed all review comments

**Comment by blegat** [comment] 2024-03-26 13:52
@whedon generate pdf

**Comment by blegat** [comment] 2024-03-26 13:52
@editorialbot generate pdf

**Comment by lucaferranti** [comment] 2024-03-26 15:41
@schillic I see you have one box unchecked, could you take a final look and confirm if it's good to go?

**Comment by schillic** [comment] 2024-04-08 08:46
Thanks for the new version. There are still some issues with the code in the paper. I think they should be fixed, at least the one marked with :one:. The ones marked with :two: should be fixed as well, but I may have forgotten to execute something. The one marked with :three: is minor because this code block cannot be executed anyway.
I also found a few minor typos and typesetting comments.

#### p. 2
- "a code" -> "code"
- "to silently returns" -> "to silently return"
- bottom left "Using `a.num =` ..." does not look great. Maybe you can remove the line break before "Using".
- :three: first code block on the right (`function mul!!(a::Rational{S}, b::Rational{T})`) is missing `where {S,T}`

#### p. 3
- "always return" -> "always returns"
- list in front of "will be available": first three lines should probably end with a comma

#### p. 4
- :one: last code block: 3x `typeof` -> `eltype`
- :two: last code block: `@allocated buffered_operate!(buf, add_mul, c, A, b)` crashes
```julia
ERROR: MethodError: no method matching buffered_operate!(::BigInt, ::typeof(add_mul),
::Vector{BigInt}, ::Matrix{BigInt}, ::Vector{BigInt})

Closest candidates are:
 buffered_operate!(::Nothing, ::Any...)
  @ Main REPL[58]:1
 buffered_operate!(::BigInt, ::typeof(add_mul), ::BigInt, ::BigInt, ::BigInt)
  @ Main REPL[60]:1
```

#### p. 5
- :two: last code block: last two commands crash (probably same problem as above)
- reference [9]: capitalization of Julia and JuMP

**Comment by blegat** [comment] 2024-04-08 11:44
@schillic Thanks again for the review! the lines defining `buffered_operate!` are excerpt from the code of MA and do not have to be executed. I clarified it and added the namespace in front so that executing them does not cause issue. Let me know if the new version addresses your concerns

**Comment by blegat** [comment] 2024-04-08 11:44
@editorialbot generate pdf

**Comment by schillic** [comment] 2024-04-08 12:33
Thanks for clarifying!
I ticked off my missing box and this is good to go from my side. Congrats!

(Just a minor comment: You added a typo ("conventioni"), and the remaining `@allocated` prints 3252504 instead of 0 the first time; since you changed the other occurrence to `@ballocated`, maybe do that here as well.)

**Comment by blegat** [comment] 2024-04-09 06:23
@schillic Thanks again, corrected!

**Comment by blegat** [comment] 2024-04-09 06:23
@editorialbot generate pdf

**Comment by schillic** [comment] 2024-04-09 06:33
@lucaferranti, I think you can do your magic.

**Comment by lucaferranti** [comment] 2024-04-09 11:37
@editorialbot check references

**Comment by lucaferranti** [comment] 2024-04-09 11:39
@blegat to finalize the submission:

- could you check if some of the references with missing DOIs would have some DOI?

- Could you make a patch release with up-to-date version of software and paper and archive that to zenodo (if not already)

- post here the zenodo DOI

**Comment by lucaferranti** [comment] 2024-04-09 11:39
@editorialbot recommend-accept

**Comment by blegat** [comment] 2024-04-18 10:47
> could you check if some of the references with missing DOIs would have some DOI?

I checked, they don't

> Could you make a patch release with up-to-date version of software and paper and archive that to zenodo (if not already)

Done

> post here the zenodo DOI

doi.org/10.5281/zenodo.10985724

**Comment by lucaferranti** [comment] 2024-04-18 12:48
@editorialbot commands

**Comment by lucaferranti** [comment] 2024-04-18 12:48
@editorialbot set v1.4.3 as version

**Comment by lucaferranti** [comment] 2024-04-18 12:49
@editorialbot set 10.5281/zenodo.10985724 as archive

**Comment by lucaferranti** [comment] 2024-04-18 12:49
@editorialbot recommend-accept

**Comment by lucaferranti** [comment] 2024-04-18 12:52
@editorialbot accept

**Comment by lucaferranti** [comment] 2024-04-18 13:03
@xuanxu @arfon do you have any idea why it might be failing now?

**Comment by lucaferranti** [comment] 2024-04-18 14:55
Congratulations @blegat for the publication :tada: 

Ans thannk you @schillic and @ksil for the review effort!

**Closed by lucaferranti** 2024-04-18 14:55 UTC
Labels: Ruby, TeX, Julia, review, accepted, author action required, recommend-accept, published

**Comment by blegat** [comment] 2024-04-18 16:13
Thank you all for your time as editor and reviewer for this paper !

**Comment by blegat** [comment] 2024-04-23 08:36
@lucaferranti @xuanxu @arfon I think there is an issue with the editorial bot.
The DOI used in his message https://github.com/JuliaCon/proceedings-review/issues/93#issuecomment-2064081312 is correct:
```
https://doi.org/10.21105/jcon.00093
```
but the DOI used in the badges of its last messages https://github.com/JuliaCon/proceedings-review/issues/93#issuecomment-2064107427 is not:
```
https://doi.org/10.21105/jcon.0093
```
There is also a `0` missing for the status badge url:
```
https://proceedings.juliacon.org/papers/10.21105/jcon.0093/status.svg
```

**Comment by lucaferranti** [comment] 2024-04-23 08:49
Ok, so I took a look and, unless I am missing something, the only place with the incorrect DOI is the last comment above. Everywhere else, on the website, on the xml metadata, it seems to be correct.

So this should be only a minor inconvenience and should not mess up any metadata. For now, this is the correct link

```
https://proceedings.juliacon.org/papers/10.21105/jcon.00093/status.svg
```

Thanks for reporting this though, will look into it! The issue seems to be that one trailing zero went missing (0093 vs 00093)

**Comment by blegat** [comment] 2024-04-23 09:15
Thanks for verifying that everything is correct. Indeed seems that only this generated message is affected
