### ISSUE TITLE
[REVIEW]: Causal.jl: A Modeling and Simulation Framework for Causal Models

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#71] opened 2021-02-11 15:44 UTC
**Submitting author:** @zekeriyasari (<a href="http://orcid.org/0000-0003-4070-9666">Zekeriya SARI</a>)
**Repository:** <a href="https://github.com/zekeriyasari/Causal.jl" target ="_blank">https://github.com/zekeriyasari/Causal.jl</a>
**Version:** v0.3.5
**Reviewer:** @cscherrer, @YingboMa
**Archive:** <a href="https://doi.org/10.5281/zenodo.5759681" target="_blank">10.5281/zenodo.5759681</a>

## Status

[![status](https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8/status.svg)](https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8"><img src="https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8/status.svg)](https://proceedings.juliacon.org/papers/0433c77d4edc08ab78c43f475af770d8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zekeriyasari/Causal.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cscherrer & @YingboMa, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @matbesancon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zekeriyasari/Causal.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@zekeriyasari) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [ ] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zekeriyasari/Causal.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@zekeriyasari) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [ ] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment] 2021-02-11 15:44
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cscherrer, @YingboMa it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-02-11 15:45
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.42 s (385.2 files/s, 70392.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             22              0             15          12915
Julia                           69           1310            669           6715
Markdown                        37            277              0           2419
TOML                             6            444              3           2035
TeX                             22            203             71           1397
Jupyter Notebook                 2              0           1076            118
YAML                             5             19              6             92
-------------------------------------------------------------------------------
SUM:                           163           2253           1840          25691
-------------------------------------------------------------------------------


Statistical information for the repository 'ba2a8a58fbbba6922f9db297' was
gathered on 2021/02/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zekeriya                         3             6             10            0.21
zekeriya.sari                   86          3504           4067           99.79

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment] 2021-02-11 15:45
PDF failed to compile for issue #71 with the following error: 

 Can't find any papers to compile :-(

**Comment by matbesancon** [comment] 2021-02-11 15:46
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-02-11 15:46
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-02-11 15:46
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: :point_left:

**Comment by YingboMa** [comment] 2021-02-11 17:58
Links for JuliaCon conflict of interest policy and JuliaCon code of conduct don't seem to work.

**Comment by matbesancon** [comment] 2021-02-11 18:03
Sorry yes we are fixing some of the links now

https://juliacon.github.io/proceedings-guide/reviewer/#conflict_of_interest
https://juliacon.github.io/proceedings-guide/reviewer/#code_of_conduct

**Comment by matbesancon** [comment] 2021-02-25 15:15
are there any blockers on the review? Links should work now

**Comment by whedon** [comment] 2021-02-25 15:44
:wave: @YingboMa, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-02-25 15:44
:wave: @cscherrer, please update us on how your review is going (this is an automated reminder).

**Comment by cscherrer** [comment] 2021-03-11 21:05
Hi, I've annotated the PDF with some feedback here:
[causal-juliacon-annotated.pdf](https://github.com/JuliaCon/proceedings-review/files/6125944/causal-juliacon-annotated.pdf)

Some of this is outside my area of expertise, but I hope the feedback can be helpful in strengthening the paper. Please let me know if any of my handwriting is too messy to read, I can type it out if that's the case :)

**Comment by zekeriyasari** [comment] 2021-03-12 07:40
Thank you for your feedback @cscherrer . The feedback will definitely be helpful to improve the paper. I did not have any difficulty with reading your handwriting. All are clear.

**Comment by matbesancon** [comment] 2021-04-22 14:18
Hi @zekeriyasari, how are things on your side? Did you make progress on updating the paper after the reviews?

**Comment by zekeriyasari** [comment] 2021-04-22 20:14
IHi @matbesancon  

I am almost finished with the updates of the review by @cscherrer . Actually, I was hoping to get reviews also by @YingboMa . I wonder what is the deadline for the submission of the updated article?

**Comment by zekeriyasari** [comment] 2021-04-25 15:18
Hi @matbesancon

I am finished with the updates. I have just committed the updates to the repository. In the commit is also included a file titled `answers.pdf` that includes the specific answers of questions/comments of the review by @cscherrer.

**Comment by matbesancon** [comment] 2021-05-06 14:07
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-05-06 14:07
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-05-06 14:07
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: :point_left:

**Comment by matbesancon** [comment] 2021-05-06 14:09
@cscherrer let us know if you have comments following the modifications and answers
@YingboMa you can also make your review on the new version posted above

**Comment by matbesancon** [comment] 2021-06-03 14:09
bump

**Comment by cscherrer** [comment] 2021-06-07 22:12
Thanks @matbesancon for the bump, and thank you @zekeriyasari for the updates. It's looking good to me!

**Comment by YingboMa** [comment] 2021-06-08 21:12
Sorry for the late reply. I only have a few minor comments on this paper, and overall, I think this paper is really solid. Though, I am not familiar with causal modeling either.

1. Could you write a bit more on the connection between the sampling by the model clock and the time stepping of the differential equation solvers?
2. There are a few times where the space before the open parenthesis is missing:
![image](https://user-images.githubusercontent.com/17304743/121257734-09bfd980-c87c-11eb-941a-097465a5cae9.png)
3. Do the strategies of breaking up algebraic loops suggested in Section 2.4 compromise the accuracy of the model?

**Comment by matbesancon** [comment] 2021-06-17 14:07
thanks Yingbo for the review!
@zekeriyasari let us know when you've worked out the changes

**Comment by zekeriyasari** [comment] 2021-07-04 14:10
Hi @matbesancon

I am done with the updates. I have just committed the updates to the repository. Similar to the previous case, in the commit is also included a jupyter notebook titled [answers2.ipynb](https://github.com/zekeriyasari/Causal.jl/blob/juliacon/paper/answers2.ipynb) that includes the specific answers of questions/comments of the review by @YingboMa

**Comment by zekeriyasari** [comment] 2021-07-04 14:14
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-04 14:14
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by matbesancon** [comment] 2021-07-04 15:38
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-04 15:38
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by matbesancon** [comment] 2021-07-04 15:43
@zekeriyasari were there some changes to come of the files in `paper`? if yes that seems to have caused some error, maybe a file error or something? Otherwise, I'd suggest trying again tomorrow just in case

**Comment by zekeriyasari** [comment] 2021-07-04 15:53
@matbesancon I just added two files in `paper` folder: `answers2.ipynb` and `algebraicloop.svg` (this is included in `answers2.ipynb`). Nothing else. And, I can compile `paper.tex` using ` latexmk -bibtex -pdf paper.tex` without a problem.

**Comment by matbesancon** [comment] 2021-07-05 08:51
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-05 08:51
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by zekeriyasari** [comment] 2021-07-05 10:46
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-05 10:46
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by zekeriyasari** [comment] 2021-07-05 10:54
Hi, @matbesancon 

I deleted all the files related to the answers to the reviewers from `paper` folder. But, still, pdf seems not to be generated. I could not understand what goes wrong. Anything else I can do on my side?

**Comment by matbesancon** [comment] 2021-07-05 15:01
no I'm not sure. @arfon do you have an idea what could cause this?

**Comment by arfon** [comment] 2021-07-06 11:42
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 11:43
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by arfon** [comment] 2021-07-06 11:47
> no I'm not sure. @arfon do you have an idea what could cause this?

It looks like @whedon was removed from this repo and https://github.com/JuliaCon/proceedings-papers a couple of weeks ago, perhaps when a 2FA requirement was added to the JuliaCon GitHub organization? This means Whedon can no longer push papers to the https://github.com/JuliaCon/proceedings-papers repo.

**Comment by arfon** [comment] 2021-07-06 11:56
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 11:56
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by arfon** [comment] 2021-07-06 11:58
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 11:58
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by arfon** [comment] 2021-07-06 12:00
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 12:00
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by arfon** [comment] 2021-07-06 12:05
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 12:05
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-06 12:05
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment] 2021-07-06 12:06
@matbesancon – I set up 2FA on Whedon's account. Should be fixed now.

**Comment by matbesancon** [comment] 2021-07-06 12:07
perfect thank you!

**Comment by zekeriyasari** [comment] 2021-07-06 12:11
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-07-06 12:11
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-06 12:11
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: :point_left:

**Comment by zekeriyasari** [comment] 2021-07-06 12:13
@matbesancon I added answer files (answers to the reviewers) back to the repo.

**Comment by cscherrer** [comment] 2021-10-21 16:01
Sorry for the delay, looks good to me. Thanks @zekeriyasari for the updates and response :)

**Comment by matbesancon** [comment] 2021-12-02 15:23
thanks both for the reviews!
@zekeriyasari can you confirm this is good to go?

**Comment by zekeriyasari** [comment] 2021-12-03 18:30
Thank you @cscherrer  @YingboMa for all your contributions. 
And, @matbesancon that is good to go. :+1: Thank you.

**Comment by matbesancon** [comment] 2021-12-05 09:15
@whedon accept

**Comment by whedon** [comment] 2021-12-05 09:15
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by matbesancon** [comment] 2021-12-05 09:15
@whedon recommend-accept

**Comment by whedon** [comment] 2021-12-05 09:15
No archive DOI set. Exiting...

**Comment by matbesancon** [comment] 2021-12-05 09:16
@whedon commands

**Comment by whedon** [comment] 2021-12-05 09:16
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment] 2021-12-05 09:16
@whedon check references

**Comment by matbesancon** [comment] 2021-12-05 09:18
@whedon check references

**Comment by matbesancon** [comment] 2021-12-05 09:20
@whedon accept deposit=true

**Comment by whedon** [comment] 2021-12-05 09:20
No archive DOI set. Exiting...

**Comment by matbesancon** [comment] 2021-12-05 09:20
@whedon recommend-accept

**Comment by whedon** [comment] 2021-12-05 09:20
No archive DOI set. Exiting...

**Comment by matbesancon** [comment] 2021-12-05 09:22
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment] 2021-12-05 09:22
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-12-05 09:23
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00071/jcon.00071/10.21105.jcon.00071.pdf) :page_facing_up: :point_left:

**Comment by matbesancon** [comment] 2021-12-05 09:27
@whedon recommend-accept from branch juliacon

**Comment by whedon** [comment] 2021-12-05 09:27
No archive DOI set. Exiting...

**Comment by matbesancon** [comment] 2021-12-05 09:30
@zekeriyasari can you post the version of the code corresponding to the submission on Zenodo?
Once it's done, can you post the corresponding DOI here?
see https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by zekeriyasari** [comment] 2021-12-05 16:12
@matbesancon Here is the doi: 
https://zenodo.org/badge/latestdoi/239842368

**Comment by matbesancon** [comment] 2021-12-05 20:11
@whedon set 10.5281/zenodo.5759681 as archive

**Comment by whedon** [comment] 2021-12-05 20:11
OK. <a href="https://doi.org/10.5281/zenodo.5759681" target="_blank">10.5281/zenodo.5759681</a> is the archive.

**Comment by matbesancon** [comment] 2021-12-05 20:11
@whedon set v0.3.5 as version

**Comment by whedon** [comment] 2021-12-05 20:11
OK. v0.3.5 is the version.

**Comment by matbesancon** [comment] 2021-12-05 20:12
@whedon check references

**Comment by matbesancon** [comment] 2021-12-05 20:16
@whedon check references

**Comment by matbesancon** [comment] 2021-12-05 20:25
@whedon recommend-accept

**Comment by whedon** [comment] 2021-12-05 20:25
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2021-12-05 20:26
PDF failed to compile for issue #71 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by matbesancon** [comment] 2021-12-05 20:26
@whedon check references from branch from branch juliacon

**Comment by whedon** [comment] 2021-12-05 20:26
```
Attempting to check references... from custom branch from
```

**Comment by matbesancon** [comment] 2021-12-05 20:27
@whedon check references from branch juliacon

**Comment by whedon** [comment] 2021-12-05 20:27
```
Attempting to check references... from custom branch juliacon
```

**Comment by whedon** [comment] 2021-12-05 20:27
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.889971 is OK

MISSING DOIs

- 10.1243/0959651021541417 may be a valid DOI for title: HYBRSIM—a modelling and simulation environment for hybrid bond graphs
- 10.3384/ecp09430137 may be a valid DOI for title: Higher-order non-causal modelling and simulation of structurally dynamic systems
- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.1109/72.896794 may be a valid DOI for title: Adaptive structures with algebraic loops
- 10.1016/b978-1-904275-26-8.50019-1 may be a valid DOI for title: Digital signal processing

INVALID DOIs

- None
```

**Comment by matbesancon** [comment] 2021-12-05 20:28
@zekeriyasari can you check the DOIs above?

**Comment by zekeriyasari** [comment] 2021-12-05 20:54
@matbesancon The DOIs above are corrected now.

**Comment by matbesancon** [comment] 2021-12-05 20:58
@whedon check references from branch juliacon

**Comment by whedon** [comment] 2021-12-05 20:59
```
Attempting to check references... from custom branch juliacon
```

**Comment by whedon** [comment] 2021-12-05 20:59
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1243/0959651021541417 is OK
- 10.3384/ecp09430137 is OK
- 10.1137/141000671 is OK
- 10.1109/72.896794 is OK
- 10.5281/zenodo.889971 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by matbesancon** [comment] 2021-12-05 21:09
@whedon recommend-accept from branch juliacon

**Comment by whedon** [comment] 2021-12-05 21:09
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2021-12-05 21:09
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1243/0959651021541417 is OK
- 10.3384/ecp09430137 is OK
- 10.1137/141000671 is OK
- 10.1109/72.896794 is OK
- 10.5281/zenodo.889971 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-12-05 21:09
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/45

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/45, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch juliacon 
```

**Comment by matbesancon** [comment] 2021-12-05 21:13
@whedon accept deposit=true from branch juliacon

**Comment by whedon** [comment] 2021-12-05 21:13
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment] 2021-12-05 21:14
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/46
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00071](https://doi.org/10.21105/jcon.00071)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by matbesancon** [comment] 2021-12-05 21:14
perfect, thank you @cscherrer and @YingboMa, and congrats @zekeriyasari

**Comment by whedon** [comment] 2021-12-05 21:15
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00071/status.svg)](https://doi.org/10.21105/jcon.00071)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00071">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00071/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00071/status.svg
   :target: https://doi.org/10.21105/jcon.00071
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00071/status.svg)](https://doi.org/10.21105/jcon.00071)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon

**Closed by matbesancon** 2021-12-05 21:14 UTC
Labels: Julia, review, Jupyter Notebook, accepted, recommend-accept, published

**Comment by matbesancon** [comment] 2022-01-27 16:03
Hi @zekeriyasari, there is an issue with the formatting, can you remove the backslashes from the title in the yml file and let us know.
The problem is that this is also copied to the paper title: https://proceedings.juliacon.org/papers/10.21105/jcon.00071
and to the bibtex entry
Please let us know when this is done

**Comment by zekeriyasari** [comment] 2022-01-29 16:40
Hi @matbesancon The backslashes are removed now. Thank you for your interest.
